version: "3.3"
   
services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./elasticSearch:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
